name: inception

services:
  wordpress:
    image: wordpress:1.0
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception_network
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    image: mariadb:1.0
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception_network
    restart: always
    env_file:
      - ".env"
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    image: nginx:1.0
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always
    env_file:
      - ".env"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
      - mariadb

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/iduman/data/wordpress
      o: bind
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/iduman/data/mariadb
      o: bind

networks:
  inception_network:
    driver: bridge
    name: inception_network
